# Project: Practicas-primer-parcial
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = practicas/1er-parcial/test.o test-2.o test3.o
LINKOBJ  = practicas/1er-parcial/test.o test-2.o test3.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Practicas-primer-parcial.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

practicas/1er-parcial/test.o: practicas/1er-parcial/test.cpp
	$(CPP) -c practicas/1er-parcial/test.cpp -o practicas/1er-parcial/test.o $(CXXFLAGS)

test-2.o: test-2.cpp
	$(CPP) -c test-2.cpp -o test-2.o $(CXXFLAGS)

test3.o: test3.cpp
	$(CPP) -c test3.cpp -o test3.o $(CXXFLAGS)
